services:
  realdebrid-blackhole:
    container_name: realdebrid-blackhole
    image: ghcr.io/sigreer/realdebrid-blackhole:latest
    user: "568"
    volumes:
      - ${HOST_TORRENTFILE_DIR}:${CONTAINER_TORRENTFILE_DIR}
      - ${HOST_OUTPUT_DIR}:${CONTAINER_OUTPUT_DIR}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REALDEBRID_APIKEY=${REALDEBRID_APIKEY}
      - CONTAINER_TORRENTFILE_DIR=${CONTAINER_TORRENTFILE_DIR}
      - CONTAINER_OUTPUT_DIR=${CONTAINER_OUTPUT_DIR}
